### import modules for numpy

In [1]:
import numpy as np

In [2]:
wines = np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)

### What is its size?

In [3]:
wines.shape

(1599, 12)

### How many wine data rows here?

In [4]:
wines.shape[0]

1599

### How many wine data columns here?


In [5]:
wines.shape[1]

12

### How many dimensions?

In [6]:
wines.ndim

2

### What is the type of wines?


In [7]:
type(wines)

numpy.ndarray

### What is the data type of wines data?

In [8]:
wines.dtype

dtype('float64')

### Show top 5 rows

In [9]:
wines[:5,:]

array([[7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00,       nan],
       [7.800e+00, 8.800e-01, 0.000e+00, 2.600e+00, 9.800e-02, 2.500e+01,
        6.700e+01, 9.968e-01, 3.200e+00, 6.800e-01, 9.800e+00,       nan],
       [7.800e+00, 7.600e-01, 4.000e-02, 2.300e+00, 9.200e-02, 1.500e+01,
        5.400e+01, 9.970e-01, 3.260e+00, 6.500e-01, 9.800e+00,       nan],
       [1.120e+01, 2.800e-01, 5.600e-01, 1.900e+00, 7.500e-02, 1.700e+01,
        6.000e+01, 9.980e-01, 3.160e+00, 5.800e-01, 9.800e+00,       nan],
       [7.400e+00, 7.000e-01, 0.000e+00, 1.900e+00, 7.600e-02, 1.100e+01,
        3.400e+01, 9.978e-01, 3.510e+00, 5.600e-01, 9.400e+00,       nan]])

### What is the value at 3rd row, 4th column of wine data?

In [10]:
wines[2,3]

2.3

### Select first 3 items in 4th column

In [11]:
wines[:3,3]

array([1.9, 2.6, 2.3])

### Show 1st column

In [12]:
wines[:,0]

array([7.4, 7.8, 7.8, ..., 6.3, 5.9, 6. ])

### Show 2nd row

In [13]:
wines[1,:]

array([ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    , 67.    ,
        0.9968,  3.2   ,  0.68  ,  9.8   ,     nan])

### Select items from rows 1 to 3 and 5th column


In [14]:
wines[1:4,4]

array([0.098, 0.092, 0.075])

### Change 1st value in wines to 100

In [15]:
wines[0,0]

7.4

In [16]:
wines[0,0]=100
wines[0,0]

100.0

###  change it back to 7.4 and print

In [17]:
wines[0,0]=7.4

## 1-Dimensional Numpy Arrays

### Select 4th row all column values

In [18]:
a = wines[3,:]

### display its value

In [19]:
a

array([11.2  ,  0.28 ,  0.56 ,  1.9  ,  0.075, 17.   , 60.   ,  0.998,
        3.16 ,  0.58 ,  9.8  ,    nan])

### show 2nd value


In [20]:
a[1]

0.28

### Convert wine data to integer values and show it

In [21]:
wines.astype(int)

array([[          7,           0,           0, ...,           0,
                  9, -2147483648],
       [          7,           0,           0, ...,           0,
                  9, -2147483648],
       [          7,           0,           0, ...,           0,
                  9, -2147483648],
       ...,
       [          6,           0,           0, ...,           0,
                 11, -2147483648],
       [          5,           0,           0, ...,           0,
                 10, -2147483648],
       [          6,           0,           0, ...,           0,
                 11, -2147483648]])

## Vectorization Operations

### Increase wine quality score (output variable) by 10

In [22]:
wines[:,11]

array([nan, nan, nan, ..., nan, nan, nan])

### Increase by 10

In [23]:
wines[:,11]+=10

### Display update score


In [24]:
wines[:,11]

array([nan, nan, nan, ..., nan, nan, nan])

### Multiply alcohol of all wine data by 3 times

In [25]:
wines[:,10]*=3

### Show updated alcohol column

In [26]:
wines[:,10]

array([28.2, 29.4, 29.4, ..., 33. , 30.6, 33. ])

### Add quality column by itselt

In [27]:
wines[:,11]+wines[:,11]

array([nan, nan, nan, ..., nan, nan, nan])

### Multiply alcohol and wine quality columns. It will perform element wise multiplication

In [28]:
wines[:,11]*wines[:,11]

array([nan, nan, nan, ..., nan, nan, nan])

## Broadcasting

### Add every row of wines data with a random array of values

In [29]:
rand_array= np.random.rand(12)

### Show rand_array

In [30]:
rand_array

array([0.02040216, 0.26064878, 0.91209823, 0.49145081, 0.01888664,
       0.12347569, 0.22467662, 0.60465184, 0.61851249, 0.20670601,
       0.83757304, 0.3259706 ])

### add wines and rand_array

In [31]:
wines+rand_array

array([[ 7.42040216,  0.96064878,  0.91209823, ...,  0.76670601,
        29.03757304,         nan],
       [ 7.82040216,  1.14064878,  0.91209823, ...,  0.88670601,
        30.23757304,         nan],
       [ 7.82040216,  1.02064878,  0.95209823, ...,  0.85670601,
        30.23757304,         nan],
       ...,
       [ 6.32040216,  0.77064878,  1.04209823, ...,  0.95670601,
        33.83757304,         nan],
       [ 5.92040216,  0.90564878,  1.03209823, ...,  0.91670601,
        31.43757304,         nan],
       [ 6.02040216,  0.57064878,  1.38209823, ...,  0.86670601,
        33.83757304,         nan]])