In [1]:
import numpy as np

In [2]:
wine = np.genfromtxt("winequality-red.csv",delimiter=";",skip_header=1)

In [44]:
wine[high_quality]

array([], shape=(0, 12), dtype=float64)

In [3]:
wine[:,3].sum()

4059.55

In [4]:
wine.sum(axis=0)

array([13303.1    ,   843.985  ,   433.29   ,  4059.55   ,   139.859  ,
       25384.     , 74302.     ,  1593.79794,  5294.47   ,  1052.38   ,
       16666.35   ,         nan])

In [5]:
wine.sum(axis=1)

array([nan, nan, nan, ..., nan, nan, nan])

In [6]:
wine.sum(axis=1).shape

(1599,)

In [7]:
wine[:,3].astype(int)

array([1, 2, 2, ..., 2, 2, 3])

In [8]:
np.max(wine[:,3].astype(int))

15

In [9]:
np.min(wine[:,3].astype(int))

0

In [10]:
np.mean(wine[:,3])

2.53880550343965

In [11]:
np.percentile(wine[:,3],25)

1.9

In [12]:
np.percentile(wine[:,3],75)

2.6

In [13]:
wine.mean(axis=0)

array([ 8.31963727,  0.52782051,  0.27097561,  2.5388055 ,  0.08746654,
       15.87492183, 46.46779237,  0.99674668,  3.3111132 ,  0.65814884,
       10.42298311,         nan])

In [14]:
wine[:,11]>5

array([False, False, False, ..., False, False, False])

In [15]:
wine[:,11]>7

array([False, False, False, ..., False, False, False])

In [47]:
np.any((wine[:,11]>7)==True)

False

In [53]:
high_quality=wine[:3,11]>7
high_quality

array([False, False, False])

In [60]:
high_quality

array([False, False, False])

In [57]:
high_quality_and_alcohol = (wine[:,10]>10)&(wine[:,11]>7)
wine[high_quality_and_alcohol,10:]

array([], shape=(0, 2), dtype=float64)

In [20]:
wh_wine = np.genfromtxt("winequality-white.csv",delimiter=";",skip_header=1)

In [21]:
wh_wine.shape

(4898, 12)

In [22]:
all_wine = np.vstack((wine,wh_wine))
all_wine.shape

(6497, 12)

In [23]:
data2 = np.concatenate((wine,wh_wine),axis=0)
data2.shape

(6497, 12)

In [24]:
np.transpose(wine).shape

(12, 1599)

In [25]:
wine.ravel()

array([ 7.4 ,  0.7 ,  0.  , ...,  0.66, 11.  ,   nan])

In [26]:
wine.ravel().shape

(19188,)

In [27]:
wine[1,:].reshape((2,6))

array([[ 7.8   ,  0.88  ,  0.    ,  2.6   ,  0.098 , 25.    ],
       [67.    ,  0.9968,  3.2   ,  0.68  ,  9.8   ,     nan]])

In [28]:
sort_alcohol = np.sort(wine[:,10])

In [29]:
sort_alcohol

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

In [30]:
wine[:,10].sort()

In [31]:
wine[:,10]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])

In [32]:
sort_alcohol_desc = np.sort(wine[:,10])[::-1]

In [33]:
sort_alcohol_desc

array([14.9, 14. , 14. , ...,  8.5,  8.4,  8.4])

In [34]:
wine[:,10]

array([ 8.4,  8.4,  8.5, ..., 14. , 14. , 14.9])